### PR TITLE
Tests/formatting

### PR DESCRIPTION
**Pull request by VascoSch92**
Hey,

now all the tests are parametrised. 

This is quite useful because it makes easy to quickly add more tests. 

In addition, pytest generates exactly one test for each test case. This way you can see exactly which test case is causing the test to fail. That is very useful in case of nasty bugs ;-)

### CODE REVIEW

**Comment by Diapolo10** [comment]
There are too many exceptions for me to add to SonarQube whitelist, would you mind swapping the address literals to constants, for example something like:

```py
IPV6_ADDRESSES = [
    '2606:4700:4700::1111',
    ...
]

TEST_CASES_IPV6 = [
    IPv6(),
    IPv6(IPV6_ADDRESSES[0]),
    IPv6(IPV6_ADDRESSES[0], 80),
    IPv6(f'[{IPV6_ADDRESSES[0]}]:80'),
    IPv6(f'[{IPV6_ADDRESSES[0]}]:80', 8080),
]
```

That way I wouldn't need to manually approve a hundred different ones.

**Comment by Diapolo10** [comment]
Oh yeah, apparently I've forgotten to replace `pylint` and `flake8` in this project with Ruff. I should probably get to it.

**Review by Diapolo10 — CHANGES_REQUESTED** [review]
I did my changes and merged them to your branch to make your life a little easier.

**Comment by VascoSch92** [comment]
> > There are too many exceptions for me to add to SonarQube whitelist, would you mind swapping the address literals to constants, for example something like:
> > ```python
> > IPV6_ADDRESSES = [
> >     '2606:4700:4700::1111',
> >     ...
> > ]
> > 
> > 
> > 
> > TEST_CASES_IPV6 = [
> >     IPv6(),
> >     IPv6(IPV6_ADDRESSES[0]),
> >     IPv6(IPV6_ADDRESSES[0], 80),
> >     IPv6(f'[{IPV6_ADDRESSES[0]}]:80'),
> >     IPv6(f'[{IPV6_ADDRESSES[0]}]:80', 8080),
> > ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That way I wouldn't need to manually approve a hundred different ones.
> 
> Yes, no problem

I tried to do as you suggested and it is not working... Can you add the exception manually? Or can I do that?

**Review by Diapolo10 — CHANGES_REQUESTED** [review]
That's good, just gotta do the same for the other two files now

**Comment by Diapolo10** [comment]
I'll take a better look after work

**Comment by Diapolo10** [comment]
It was nothing complicated, the test result simply included the quotes of the string literal. An easy fix was to make Python treat the IP address via `repr` instead of `str` in the test case.

**Comment by VascoSch92** [comment]
can we not just add the the exception? The code will be much cleaner then....

**Comment by Diapolo10** [comment]
Okay, fine, I'll spend the weekend telling Sonarcloud to ignore the false positives. You can revert the changes to the addresses.

**Comment by VascoSch92** [comment]
> Okay, fine, I'll spend the weekend telling Sonarcloud to ignore the false positives. You can revert the changes to the addresses.

Actually, I saw that you did already a lot in the code. Let's change the code ;-) I will do the rest this week

sorry for the misunderstanding

**Comment by VascoSch92** [comment]
Here we are :-)

**Review by Diapolo10 — APPROVED** [review]
LGTM

**Comment by Diapolo10** [comment]
Not sure why the unit tests for the pull request aren't running, looking into it.

**Comment by Diapolo10** [comment]
Ah, whatever. It already passes the tests anyway, so I'll force-merge this. Dunno why it's not running in the pull request itself.

**Pull request merged**
